# Generated by Django 3.2.13 on 2022-11-11 17:16

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('sistema', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Edificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('nome', models.CharField(max_length=120)),
            ],
            options={
                'verbose_name': 'edifício',
            },
        ),
        migrations.CreateModel(
            name='EdificioSistemas',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('inicio', models.DateField()),
                ('final', models.DateField()),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificio.edificio', to_field='sid')),
                ('sistema', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='sistema.sistema')),
            ],
            options={
                'verbose_name': 'edifício sistema',
                'verbose_name_plural': 'edifícios sistemas',
                'db_table': 'edificio_edificio_sistemas',
            },
        ),
        migrations.AddField(
            model_name='edificio',
            name='sistemas',
            field=models.ManyToManyField(through='edificio.EdificioSistemas', to='sistema.Sistema'),
        ),
    ]
