# Generated by Django 3.2.13 on 2022-11-11 17:16

import config.models
from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('edificio', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ConfigGeral',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'verbose_name': 'configuração geral',
                'verbose_name_plural': 'configurações gerais',
            },
            bases=(models.Model, config.models.ConfigMixin),
        ),
        migrations.CreateModel(
            name='ConfigEdificio',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('alterado_em', models.DateTimeField(auto_now=True)),
                ('criado_em', models.DateTimeField(auto_now_add=True)),
                ('sid', models.UUIDField(default=uuid.uuid4, editable=False, unique=True)),
                ('edificio', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='edificio.edificio', to_field='sid')),
            ],
            options={
                'verbose_name': 'configuração por edifício',
                'verbose_name_plural': 'configurações por edifício',
            },
            bases=(models.Model, config.models.ConfigMixin),
        ),
    ]
